### ISSUE TITLE
scaled Flux Dev

### ISSUE THREAD

**Issue by cbresciano** [rainlizard/EasyQuantizationGUI#2]
I tried to use Flux1DevFP8 scaled to cuantisize and the first step is done perfectly, the 23.8Gb gguf transitory file is got, but the second step of quantization fails though the console says the cuantization is completed at the end. Finally no file appears, wheter transitory or cuantisized. The file used is https://huggingface.co/comfyanonymous/flux_dev_scaled_fp8_test

**Comment by rainlizard** [comment]
I can reproduce your issue using the file you linked, the error is `Return code: 3221226505` in the log. (not sure what that means)

It seems `convert.py` always converts it to a 23.8GB file, even though the file you're trying to quant is 11GB. This might be breaking it, perhaps it's not built to quantize from anything except the original one.

If you use this file instead to quantize, then it'll work: https://huggingface.co/black-forest-labs/FLUX.1-dev/blob/main/flux1-dev.safetensors

You may want to post your issues here: https://github.com/city96/ComfyUI-GGUF/issues , since this GUI is built around this: https://github.com/city96/ComfyUI-GGUF/tree/main/tools

My repo here is just the GUI which is nothing but a simple shell with buttons you can click. I don't know how it works internally.
